#pod 'AFNetworking', '~> 2.0'
#pod 'SDWebImage', '~> 3.6'
#pod 'XLForm', '~> 2.1.0'
#pod 'MBProgressHUD', '~> 0.9.1'
#pod 'BButton'
#pod 'FBSDKCoreKit', '~> 4'
#pod 'OAuth.io'
#pod 'AWSiOSSDKv2'
#pod 'AWSCognitoSync'
#pod 'NXOAuth2Client', '~> 1.2.8'
#pod 'FDKeychain', '~> 1.0.0'
pod 'FontAwesomeKit', '~> 2.1.0'
#pod 'FontAwesome-iOS'